name: Create Release PR

on:
    workflow_run:
        workflows: ['Verify']
        types:
            - completed

jobs:
    release_pr:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        name: Create PR
        permissions:
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - uses: googleapis/release-please-action@v4
              id: release-pr
              with:
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                  release-type: node
