name: Verify

on:
    push:
        branches: ['main']

env:
    EXTENSION_ZIP: wol@mnorlin.se.shell-extension.zip

jobs:
    verify:
        name: Lint code
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Lint code
              run: npm run lint
